apiVersion: v1
kind: Service
metadata:
  name: the-gate
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preview
  labels:
    app: preview
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    matchLabels:
      app: preview
  replicas: 2
  template:
    metadata:
      labels:
        app: preview
    spec:
      containers:
      - name: preview
        image: registry.cloud.okteto.net/koenverburg/site-preview
        ports:
          - containerPort: 3000
