ignores:
  - "graphql-*"
  - "classnames"
  - "@typescript-eslint/*"
  - "preact"
  - "@graphql-codegen/*"
  - "@graphql-tools/*"
  - "@types/jest"
  - "apollo-server-micro"
  - "jest-resolve-cached"
  - "isomorphic-fetch"
skip-missing: true
ignoreBinPackage: true
