projects:
  default:
    schema:
      - ${GRAPHCMS_URL}
        # headers:
        #   Authorization: "bearer ${GRAPHCMS_TOKEN}"

    extensions:
      codegen:
        generates:
          ./.generated/graphcms/graphcms.graphql:
            plugins:
              - schema-ast
          ./.generated/graphcms/types.ts:
            plugins:
              - "typescript"
              - "typescript-operations"
              - "typescript-react-apollo"
          ./.generated/graphcms/graphql.schema.json:
            plugins:
              - "introspection"
